# Tell Travis the project language.
language: c

# Route to the container-based infrastructure for a faster build.
sudo: false

# Install dependencies.
addons:
  apt:
    packages:
      - pandoc
      - texlive-xetex
  homebrew:
    packages:
      - pandoc
    casks:
      - mactex

# Configure caching of Homebrew packages.
before_cache:
    - [[ "$TRAVIS_OS_NAME" == "osx" ]] && brew cleanup
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

# Branch whitelist.
branches:
  only:
    - master

# Choose operating systems.
os:
  - linux
  - osx

# Choose compilers.
compiler:
  - clang
  - gcc

# HACK: Set the PATH environment variable for osx runs
env:
  -
  - PATH=$PATH:/Library/TeX/texbin

# HACK: fix up the build matrix
matrix:
  exclude:
    # Exclude linux jobs where PATH is set
    - os: linux
      env: PATH=$PATH:/Library/TeX/texbin
    # Exclude osx jobs where PATH is not set
    - os: osx
      env:

# Override default install.
install:
  - autoreconf --install

# Override default script.
script:
  - ./configure && make && make distcheck
