# Tell Travis the project language.
language: generic

# Route to the container-based infrastructure for a faster build.
sudo: false

# Enable caching the bundle between builds.
cache: bundler

# Branch whitelist.
branches:
  only:
    - master

# Choose operating systems.
os:
  - linux
  - osx

# Choose compilers.
compiler:
  - clang
  - gcc

install:
  - bundle install

script:
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build ./
  - ctest ./
