# Route to the container-based infrastructure for a faster build.
sudo: false

# Enable caching the bundle between builds.
cache: bundler

# Branch whitelist.
branches:
  only:
    - master

# Choose operating systems.
os:
  - linux
  - osx

script:
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build ./
  - ctest ./
