# Tell Travis the project language.
language: c

# Route to the container-based infrastructure for a faster build.
sudo: false

# Branch whitelist.
branches:
  only:
    - master

# Override default install.
install: autoreconf --install

# Define the test anchor
test: &test
  stage: test
  script:
    - ./configure
    - make
    - make check

# Define the tarball anchor
tarball: &tarball
  stage: tarball
  script:
    - ./configure
    - make
    - make dist
    - mv edutils-*.tar.gz ~
    - cd
    - tar -xzf edutils-*.tar.gz
    - cd edutils-*
    - ./configure
    - make
    - make check

# Configure job stages.
jobs:
  include:
    - <<: *test
      compiler: clang
      os: linux
    - <<: *test
      compiler: gcc
      os: linux
    - <<: *test
      compiler: clang
      os: osx
    - <<: *test
      compiler: gcc
      os: osx

    - <<: *tarball
      compiler: clang
      os: linux
    - <<: *tarball
      compiler: gcc
      os: linux
    - <<: *tarball
      compiler: clang
      os: osx
    - <<: *tarball
      compiler: gcc
      os: osx
