#!/bin/bash

# correct permissions on language directory
chmod go= $progdir/lang

# dynamically generate a function for each test in lang
for l in $progdir/lang/* ; do
  lang=`basename $l`

  for level in prelab lab solution ; do
    sol=$l/unit-$level.sol

    # dynamically create a new test function
    . /dev/stdin <<EOF
test-$lang-$level() {
  # create an output file
  local out=\$(mktemp)
  assertTrue \$?

  # execute release
  $srcdir/src/release --$level --suffix=.$lang $l
  assertTrue \$?

  # recursively query file permissions
  ls -laRF $l | awk '{if (NF>2) print \$1,\$NF}' > \$out
  assertTrue \$?

  # compute the diff with the known solution
  diff $sol \$out
  assertTrue \$?

  # HACK: req'd so that shunit2 does not report an error because the funtion
  # returned a non-zero code.
  true
}
EOF

    # add the new function to the test suite
    suite_addTest test-$lang-$level
  done
done
