#!/bin/bash

# correct permissions on language directory
chmod go= $srcdir/lang

# dynamically generate a function for each test in lang
for langdir in $srcdir/lang/* ; do
  lang=$(basename $langdir)

  sol=$langdir/unit.sol

  # dynamically create a new test function
  . /dev/stdin <<EOF
test-$lang() {
  # create an output file
  local out=\$(mktemp)
  assertTrue \$?

  # execute release
  $bindir/watchdog $testdir/watchdog/_watchdog.yml
  assertTrue \$?

  # recursively query file permissions
  ls -laRF $langdir | awk '{if (NF>2) print \$1,\$NF}' > \$out
  assertTrue \$?

  # compute the diff with the known solution
  diff $sol \$out
  assertTrue \$?

  # HACK: req'd so that shunit2 does not report an error because the funtion
  # returned a non-zero code.
  true
}
EOF

  # add the new function to the test suite
  suite_addTest test-$lang
done
