#!/usr/bin/env ruby

# frozen_string_literal: true

################################################################################
# MIT License
#
# Copyright (c) 2019 Jeremy Iverson
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
################################################################################

require 'etc'
require 'fileutils'
require 'yaml'

# rubocop:disable all
# Monkey patch so that +X behaves correctly, i.e., execute/search permission is
# affected only if the file is a directory or already had execute permission.
module FileUtils
 def symbolic_modes_to_i(mode_sym, path)  #:nodoc:
    mode = if File::Stat === path
             path.mode
           else
             File.stat(path).mode
           end
    mode_sym.split(/,/).inject(mode & 07777) do |current_mode, clause|
      target, *actions = clause.split(/([=+-])/)
      raise ArgumentError, "invalid file mode: #{mode_sym}" if actions.empty?
      target = 'a' if target.empty?
      user_mask = user_mask(target)
      actions.each_slice(2) do |op, perm|
        need_apply = op == '='
        mode_mask = (perm || '').each_char.inject(0) do |mask, chr|
          case chr
          when "r"
            mask | 0444
          when "w"
            mask | 0222
          when "x"
            mask | 0111
          when "X"
            if FileTest.directory?(path) || (current_mode & 00111) > 0
              mask | 0111
            else
              mask
            end
          when "s"
            mask | 06000
          when "t"
            mask | 01000
          when "u", "g", "o"
            if mask.nonzero?
              current_mode = apply_mask(current_mode, user_mask, op, mask)
            end
            need_apply = false
            copy_mask = user_mask(chr)
            (current_mode & copy_mask) / (copy_mask & 0111) * (user_mask & 0111)
          else
            raise ArgumentError, "invalid `perm' symbol in file mode: #{chr}"
          end
        end

        if mode_mask.nonzero? || need_apply
          current_mode = apply_mask(current_mode, user_mask, op, mode_mask)
        end
      end
      current_mode
    end
  end
  private_module_function :symbolic_modes_to_i
end
# rubocop:enable all

# Policy class
class Policy
  include Comparable

  def initialize(time, mode)
    @time = time
    case mode
    when Hash
      @dir  = mode['dir']
      @file = mode['file']
    when String
      @dir  = mode
      @file = mode
    end
  end

  def <=>(other)
    time <=> other.time
  end

  def valid?
    (time - now.gmt_offset) <= now
  end

  def mode(fullpath)
    File.directory?(fullpath) ? dir : file
  end

  protected

  attr_reader :time

  private

  attr_reader :dir
  attr_reader :file
end

# Path class
class Path
  def initialize(config, fullpath, parent = nil)
    # record arguments
    %i[config fullpath parent].each do |s|
      instance_variable_set("@#{s}", binding.local_variable_get(s))
    end

    # populate instance variables in specific order
    %i[group excludes includes policy path].each do |s|
      instance_variable_set("@#{s}", send(s))
    end
  end

  def apply
    (path + children).each(&:apply)

    return if @parent.nil?

    chmod(mode, fullpath)
    chown(nil, group, fullpath)
    chmod?(mode, fullpath)
  end

  protected

  attr_reader :fullpath

  def mode
    (excluded? || !policy.max.valid? ? policy.min : policy.max).mode(fullpath)
  end

  def group
    @group ||= @config.delete('group') || @parent&.group || ''
  end

  def policy
    @policy ||= if @config['mode']
                  [Policy.new(Time.at(0), @config.delete('mode'))]
                else
                  @parent&.policy.clone || []
                end.tap do |list|
                  list.concat(@config.map do |k, v|
                    Policy.new(k, v) if k.is_a?(Time)
                  end.compact)
                end
  end

  def excludes
    @excludes ||= (@parent&.excludes.clone || []).tap do |list|
      list.concat(@config.delete('exclude')&.map do |e|
        Dir.glob(File.join(fullpath, e))
      end&.flatten || [])
    end
  end

  def includes
    @includes ||= (@parent&.includes.clone || []).tap do |list|
      list.concat(@config.delete('include')&.map do |i|
        Dir.glob(File.join(fullpath, i))
      end&.flatten || [])
    end
  end

  private

  def chmod(mode, fullpath)
    return unless chmod?(mode, fullpath)

    FileUtils.chmod(mode, fullpath, verbose: true)
  end

  def chown(user, group, fullpath)
    return unless chown?(user, group, fullpath)

    FileUtils.chown(nil, group, fullpath, verbose: true)
  end

  def path
    @path ||= @config.map do |k, v|
      Path.new(v, File.join(fullpath, k), self) if k.is_a?(String)
    end.compact
  end

  def children
    @children ||= dir_children(fullpath).map do |c|
      cpath = File.join(fullpath, c)
      Path.new(@config, cpath, self) unless path?(cpath)
    end.compact
  end

  def dir_children(fullpath)
    @parent && Dir.exist?(fullpath) ? Dir.children(fullpath) : []
  end

  def chmod?(mode, filepath)
    smode = File.stat(filepath).mode & 0o07777
    imode = FileUtils.send(:symbolic_modes_to_i, mode, filepath)
    smode != imode
  end

  def chown?(_user, group, filepath)
    return if group.empty?

    Etc.getgrnam(group).gid == File.stat(filepath).gid
  end

  def path?(fullpath)
    path.any? { |p| p.fullpath.eql?(fullpath) }
  end

  def excluded?
    excludes.include?(fullpath) && !included?
  end

  def included?
    includes.include?(fullpath)
  end
end

# ...
def now
  @now ||= Time.now
end

# Start processing
begin
  Path.new(YAML.load_file(File.join(ARGV[0], '_watchdog.yml')), ARGV[0]).apply
rescue ArgumentError => e
  puts e.message
rescue Errno::ENOENT => e
  puts e.message
end
